### PR TITLE
agent: read config from toml file

### PR DESCRIPTION
**Pull request by technoweenie**
Implements #65. As a side bonus, it's easy to tweak the other settings too if desired. Here's what my test file looked like:

```sh
$ cat ~/.tractor/config.toml
PreferredBrowser = "Google Chrome"
SocketPath = "/Users/rick/.tractor/tractor-custom.sock"
```

Some things to think about:

1. Is this fine on the Agent type? A case could be made to have some central tractor config type or package. If Agent is the main entry point, it may not be that necessary though.
2. Should the settings live under some `[[Agent]]` header?
3. Does this introduce any potential security issues? 

I believe I could add a new central config type, or start using toml `[[sections]]`, later without breaking backwards compatibility. So, I opted for the easiest solution: decoding with `*agent.Agent` directly, and not using any toml `[[sections]]`.

Also, I'm hoping https://github.com/skratchdot/open-golang/pull/27 gets merged. It'll at least clean up the change to `systray.Service`.

TODO:
* [ ] add tests!

### CODE REVIEW

**Comment by progrium** [comment]
Yeah I think an optional global config should be a top level package that owns ~/.tractor/config.toml and the agent or a workspace can use it. Maybe put agent config under an agent section.

**Comment by progrium** [comment]
Did you have possible security issues in mind?

**Comment by technoweenie** [comment]
I pulled out the config into a separate package in [70f4582](https://github.com/manifold/tractor/pull/66/commits/70f4582971dbcc584efe5aafa1945a6a9fa23c5f). However, there isn't a clean way to have default property values like:

```go
a.SocketPath = filepath.Join(a.Path, "agent.sock")
```

So in [ed019cb](https://github.com/manifold/tractor/pull/66/commits/ed019cbce25645732aba8f396fd930aa58132917), `agent.Agent` now embeds `config.Agent`. The values still get their default values based on the agent path, but they can still be overridden by the toml file.

RE: Security issues: I was just trying to think of any major consequences from allowing people to specify their browser (which can be path to an executable on linux).

**Comment by progrium** [comment]
Ok to pull in?

**Comment by technoweenie** [comment]
Yup, thanks. GH missed the notification for this for some reason.

**Pull request merged**
