### PR TITLE
specify version for hashicorp/mdns package

### PR DESCRIPTION
**Pull request by technoweenie**
This sets a version for the mdns package in `go.mod`. I'm not totally sure why it's needed though, since I'm able to build `tractor-agent` just fine. The problem comes when I start up `selfdev` and it tries to compile my workspace:

```sh
$ make dev
./local/bin/tractor-agent --dev
agent  | 2020-03-17T13:18:57.571-0600	INFO	rpc/service.go:48	agent listening at unix:///Users/rick/.tractor/agent.sock
studio | yarn run v1.22.0
studio | $ /Users/rick/p/tractor/studio/node_modules/.bin/theia start --log-level warn --plugins local-dir:../plugins/
@dev   | go: github.com/manifold/tractor@v0.0.0 requires
@dev   | 	github.com/hashicorp/mdns@v0.0.0: reading github.com/hashicorp/mdns/go.mod at revision v0.0.0: unknown revision v0.0.0
panic: exit status 1
```

I just ran `go get` as a workaround, which modified `go.mod` for me.

```sh
# no change, it's already in my gopath!
$ go get github.com/hashicorp/mdns
$ make dev
./local/bin/tractor-agent --dev
agent  | 2020-03-17T13:19:30.968-0600	INFO	rpc/service.go:48	agent listening at unix:///Users/rick/.tractor/agent.sock
studio | yarn run v1.22.0
studio | $ /Users/rick/p/tractor/studio/node_modules/.bin/theia start --log-level warn --plugins local-dir:../plugins/
agent  | 2020-03-17T13:19:31.481-0600	INFO	supervisor/supervisor.go:252	@dev: Partially => Available
@dev   | 2020-03-17T13:19:31.723-0600	DEBUG	mdns/service.go:19	discoverable via mdns
@dev   | 2020-03-17T13:19:31.723-0600	INFO	rpc/service.go:98	daemon listening at 127.0.0.1:54492
```

### CODE REVIEW

**Comment by progrium** [comment]
This is because we're using a vendored slightly patched version: https://github.com/manifold/tractor/tree/master/vnd/github.com/hashicorp/mdns

Which works because of this replace: https://github.com/manifold/tractor/blob/master/go.mod#L65

And I believe for this to work I needs v0? Not sure but that's how it works for me.

The patch prevents a log.Println happening during the main function call of the package. It also fixes a bug when ipv6 is not available that makes it just return an error instead of using the ipv4 result. The upstream repo doesn't look like a maintained package for public use (it has a "for us" vibe to it) and I didn't want to maintain a fork, so its vendor patched here for now.

**Comment by progrium** [comment]
With that in mind, does the vendor replace not work for you?

**Comment by technoweenie** [comment]
Hmm, that makes sense. It works with `make build`, but not the workspace build. I'll have to look into why it's not using taking tractor's go.mod into account.

**Comment by technoweenie** [comment]
Okay, I just had to add this to my workspace's go.mod:

https://github.com/manifold/tractor/blob/ed544ece7a063c4279399e86e9fe2040620094dd/data/workspace/go.mod#L12

**Pull request closed without merging**
